"""add image_url source dedup_hash to jobs

Revision ID: 5551a2be3174
Revises: 207b7816f6f2
Create Date: 2026-09-15 14:25:32.162666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5551a2be3174'
down_revision: Union[str, None] = '207b7816f6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_url', sa.Text(), nullable=True))
    op.alter_column('jobs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'apply_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'apply_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('jobs', 'image_url')
    # ### end Alembic commands ###
