"""add job source dedup_hash image_url

Revision ID: 65f9db7cfa7f
Revises: 5551a2be3174
Create Date: 2026-09-15 14:41:15.421324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f9db7cfa7f'
down_revision: Union[str, None] = '5551a2be3174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
